import { getThemeOrTemplate } from "./themes/index.js";
import { generateHTMLPreview } from "./html-preview.js";
import { escapeHtml } from "./utils.js";
import { COLORS } from "./constants.js";

export async function generateHtmlDocument(elements, metadata, themeId = "kyotu") {
  const theme = await getThemeOrTemplate(themeId);
  const c = theme.colors;
  const f = theme.fonts;
  const previewContent = generateHTMLPreview(elements, metadata, themeId);

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(metadata.title || "Document")}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/github.min.css">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    
    body {
      font-family: ${f.body}, Arial, sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #${c.text};
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 60px;
      background: white;
    }
    
    @media print {
      body { padding: 0; max-width: none; }
      @page { margin: 2cm; }
      .no-print { display: none !important; }
    }
    
    h1, h2, h3, h4 {
      font-family: ${f.heading}, Georgia, serif;
      color: #${c.primary};
      margin-top: 1.5em;
      margin-bottom: 0.5em;
      page-break-after: avoid;
    }
    
    h1 { font-size: 1.75em; }
    h2 { font-size: 1.4em; }
    h3 { font-size: 1.2em; }
    h4 { font-size: 1.1em; }
    
    p {
      font-family: ${f.body}, Arial, sans-serif;
      margin-bottom: 0.75em;
    }
    
    ul, ol {
      font-family: ${f.body}, Arial, sans-serif;
      margin: 0.5em 0 1em 1.5em;
    }
    
    li { margin: 0.25em 0; }
    
    code {
      font-family: ${f.mono}, 'Courier New', monospace;
      font-size: 0.9em;
      background: #${c.codeBg};
      border: 1px solid #${c.codeBorder};
      padding: 0.1em 0.4em;
      border-radius: 3px;
    }
    
    pre {
      font-family: ${f.mono}, 'Courier New', monospace;
      font-size: 0.85em;
      background: #${c.codeBg};
      border: 1px solid #${c.codeBorder};
      padding: 1em;
      border-radius: 6px;
      overflow-x: auto;
      margin: 1em 0;
      page-break-inside: avoid;
    }
    
    pre code {
      background: none;
      border: none;
      padding: 0;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 1em 0;
      font-family: ${f.body}, Arial, sans-serif;
      font-size: 0.95em;
      page-break-inside: avoid;
    }
    
    th, td {
      border: 1px solid #${c.tableBorder};
      padding: 0.5em 0.75em;
      text-align: left;
    }
    
    th {
      background: #${c.tableHeader};
      font-weight: 600;
    }
    
    td:first-child { font-weight: 500; }
    
    hr {
      border: none;
      height: 2px;
      background: #${c.muted};
      margin: 2em 0;
    }
    
    a {
      color: #${c.accent};
      text-decoration: none;
    }
    
    a:hover { text-decoration: underline; }
    
    strong { color: #${c.bold || COLORS.boldFallback}; }
    
    .title-block {
      margin-bottom: 2em;
      padding-bottom: 1em;
      border-bottom: 3px solid #${c.primary};
    }
    
    .title-block h1 {
      margin-top: 0;
      font-size: 1.75em;
    }
    
    .title-block .meta {
      color: #${c.secondary};
      font-size: 0.9em;
      margin-top: 0.5em;
    }
    
    .checklist {
      list-style: none;
      margin-left: 0;
      padding-left: 0;
    }
    
    .checklist li {
      display: flex;
      align-items: center;
      gap: 0.5em;
    }
    
    img {
      max-width: 100%;
      height: auto;
      display: block;
      margin: 1em auto;
    }
    
    .print-btn {
      position: fixed;
      top: 20px;
      right: 20px;
      background: #${c.primary};
      color: white;
      border: none;
      padding: 12px 24px;
      border-radius: 8px;
      cursor: pointer;
      font-size: 14px;
      font-weight: 600;
      box-shadow: 0 4px 12px rgba(0,0,0,0.15);
      transition: transform 0.2s, box-shadow 0.2s;
    }
    
    .print-btn:hover {
      transform: translateY(-2px);
      box-shadow: 0 6px 16px rgba(0,0,0,0.2);
    }
    
    .footer {
      margin-top: 3em;
      padding-top: 1em;
      border-top: 1px solid #e5e7eb;
      font-size: 0.85em;
      color: #${c.muted};
      text-align: center;
    }
    
    @media print {
      .footer { display: none; }
    }
  </style>
</head>
<body>
  <button class="print-btn no-print" onclick="window.print()">🖨️ Print / Save PDF</button>
  
  ${previewContent}
  
  <div class="footer no-print">
    Generated by MD2DOCX &middot; KYOTU Technology
  </div>
</body>
</html>`;

  return html;
}

export async function generateHtmlBlob(elements, metadata, themeId = "kyotu") {
  const html = await generateHtmlDocument(elements, metadata, themeId);
  return new Blob([html], { type: "text/html;charset=utf-8" });
}
